version: '3.8'

services:
  app:
    image: php:8.0-fpm
    platform: linux/amd64
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      - PHP_MEMORY_LIMIT=4096M
    command: >
      bash -c "echo 'memory_limit = 4096M' > /usr/local/etc/php/conf.d/memory-limit.ini &&
                php-fpm"

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --innodb_flush_log_at_trx_commit=2
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: